### ISSUE TITLE
Capture UUID, name and email address of submitter in UI

### ISSUE THREAD

**Issue by z-w123** [ebi-ait/sars-cov2-data-upload#24]
Would be extremely useful to have the user’s UUID (submission key), name and email address captured by the covid-utils UI - as this information would then be able to be propagated into the automated tickets that ena-virus-dataflow queue receives whenever a user makes a submission.
This would allow us to better track each user’s submission and reduce the possibility of errors when addressing these tickets.

**Comment by mcourtot** [comment]
Hi @z-w123 - can you please check on your side eg with @guycochrane and @Jeena-Rajan whether that is desired? We initially had the submitter email in the form for example, and decided to remove it.
Happy to add it again, just want to make sure this is indeed the plan.

**Comment by Jeena-Rajan** [comment]
It would be useful to have name and email address as Zahra described as otherwise, all the tickets look the same in RT (with different UUIDs though). This is so we can easily match the ticket in RT with the original email request and the submission itself in AWS. As long as this complies with GDPR of course. This will enable easy tracking of submission requests with data upload and help prevent errors on our side.

**Comment by peterwharrison** [comment]
Melanie can you confirm whether you are going to make this change (and when) so that I can have the GDPR updated before it is put into production.
______________________
Dr Peter W Harrison
Data Coordination and Presentation Coordinator
European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Cambridge, CB10 1SD, UK
E-mail: peter@ebi.ac.uk
Tel:  +44-(0)1223 492589
______________________

**Comment by dipayan1985** [comment]
@nadimm-rahman - Could we probably have a deployment window this Friday (15/05) if there are no external submitter lined up?

@peterwharrison - Depending on the deployment window we can let you know when we want to push the changes in.

/cc @mcourtot

**Comment by nadimm-rahman** [comment]
@dipayan1985 One submitter may be willing to use the tool, but have to confirm this. They most probably won't be ready for this Friday, so it's ok to have a deployment window for 15/05.

**Comment by dipayan1985** [comment]
Hi @peterwharrison 
As per the feedback received above, we will be adding name and email as mandatory fields along with the current secure key. It would be great if you can help in getting the GDPR updated. We will proceed with the deployment to production after the GDPR update is complete.
/cc @mcourtot @Jeena-Rajan

**Comment by peterwharrison** [comment]
The GDPR covers name, email and username/password for this usage. It is live so feel free to deploy.

Best wishes,

Peter
______________________
Dr Peter W Harrison
Data Coordination and Presentation Coordinator
European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Cambridge, CB10 1SD, UK
E-mail: peter@ebi.ac.uk
Tel:  +44-(0)1223 492589
______________________

**Comment by dipayan1985** [comment]
That's great. Thank you @peterwharrison

**Comment by dipayan1985** [comment]
Dev complete.
